import { MainNav } from "@/components/main-nav";
import { ThemeProvider } from "@/components/ui/theme-provider";
import type { Metadata } from "next";
import { IBM_Plex_Mono, Rubik } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rubik = Rubik({ subsets: ["latin"], variable: "--font-rubik" });
const IBMPlexMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-ibm-plex-mono",
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${rubik.variable} ${IBMPlexMono.variable} font-sans`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MainNav />
          <div className="m-auto max-w-[1200px]">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
